### ISSUE TITLE
issue with  your adapter

### ISSUE THREAD

**Issue by eXplOiD1** [nisiode/ioBroker.vis-material#1]
hello i have problems with your adapter after installing my vis is broken.
Uninstall of your adapter dont fix the problem.

[screenshot](https://www2.pic-upload.de/img/34945021/Unbenannt-1.png)

**Comment by nisiode** [comment]
what exactly do you mean by "my vis is broken"

**Comment by eXplOiD1** [comment]
You see the screenshot ?  If your widgets are installed the background on the vis editor is black all right click options are black too

**Comment by nisiode** [comment]
thats because the adapter is bringing the material css withit. thats a feature of the adapter.
